---
- name: Install and configure Jenkins on EC2
  hosts: jenkins
  become: yes

  vars:
    jenkins_repo_key_url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    jenkins_repo: "deb https://pkg.jenkins.io/debian-stable binary/"
    jenkins_url: http://localhost:8080
    jenkins_cli_dest: /tmp/jenkins-cli.jar

  tasks:

    - name: Update APT package cache
      apt:
        update_cache: yes
 
    - name: Install Java (required for Jenkins)
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Download Jenkins GPG key to trusted.gpg.d
      get_url:
        url: "{{ jenkins_repo_key_url }}"
        dest: /etc/apt/trusted.gpg.d/jenkins.asc
        mode: '0644'

    - name: Add Jenkins repository
      apt_repository:
        repo: "{{ jenkins_repo }}"
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        update_cache: yes
        state: present

    - name: Ensure Jenkins is started and enabled
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Wait for Jenkins to be available
      uri:
        url: "{{ jenkins_url }}/login"
        method: GET
        status_code: 200
        validate_certs: no
      register: jenkins_ready
      retries: 10
      delay: 5
      until: jenkins_ready.status == 200

    - name: Download Jenkins CLI jar
      get_url:
        url: "{{ jenkins_url }}/jnlpJars/jenkins-cli.jar"
        dest: "{{ jenkins_cli_dest }}"
        mode: '0755'
